Evidence_01/Models/ViewModels/PlayersViewModel.cs
using Evidence_01.CustomValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
namespace Evidence_01.Models.ViewModels
{
    public class PlayersViewModel
    {
        public int PlayerId { get; set; }
        [Required, StringLength(50), Display(Name = "Player Name")]
        public string PlayerName { get; set; }
        [Required, Display(Name = "Join Date")]
        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [LessDate]
        public DateTime JoinDate { get; set; }
        [EnumDataType(typeof(PlayerGrade))]
        public PlayerGrade? Grade { get; set; }
        public string PicturePath { get; set; }
        public HttpPostedFileBase Picture { get; set; }

        [Required]
        [ForeignKey("Sports")]
        public int SportsId { get; set; }
        public virtual Sports Sports { get; set; }
    }
}

Evidence_01/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Evidence_01.Models;
using Evidence_01.Models.ViewModels;

namespace work_01.Controllers
{
    [Authorize]
    public class PlayersController : Controller
    {
        ClubDbContext db = new ClubDbContext();
        // GET: Players
        [AllowAnonymous]
        public ActionResult Index(int page = 1)
        {
            var players = db.Players.Include("Sports");
            return View(players.OrderBy(x => x.PlayerId).ToList());
        }
        public ActionResult Create()
        {
            ViewBag.Sports = new SelectList(db.Sports, "SportsId", "SportsName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlayersViewModel evm)
        {
            if (ModelState.IsValid)
            {
                if (evm.Picture != null)
                {
                    string filepath = Path.Combine("~/Images", Guid.NewGuid().ToString() + Path.GetExtension(evm.Picture.FileName));
                    evm.Picture.SaveAs(Server.MapPath(filepath));

                    Player player = new Player
                    {
                        PlayerName = evm.PlayerName,
                        JoinDate = evm.JoinDate,
                        Grade = evm.Grade,
                        SportsId = evm.SportsId,
                        PicturePath = filepath
                    };
                    db.Players.Add(player);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Sports = new SelectList(db.Sports, "SportsId", "SportsName");
            return View(evm);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            PlayersViewModel evm = new PlayersViewModel
            {
                PlayerId = player.PlayerId,
                PlayerName = player.PlayerName,
                JoinDate = player.JoinDate,
                Grade = player.Grade,
                SportsId = player.SportsId,
                PicturePath = player.PicturePath
            };
            ViewBag.Sports = new SelectList(db.Sports, "SportsId", "SportsName", evm.SportsId);
            return View(evm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlayersViewModel evm)
        {
            if (ModelState.IsValid)
            {
                string filepath = evm.PicturePath;
                if (evm.Picture != null)
                {
                    filepath = Path.Combine("~/Images", Guid.NewGuid().ToString() + Path.GetExtension(evm.Picture.FileName));
                    evm.Picture.SaveAs(Server.MapPath(filepath));

                    Player player = new Player
                    {
                        PlayerId = evm.PlayerId,
                        PlayerName = evm.PlayerName,
                        JoinDate = evm.JoinDate,
                        Grade = evm.Grade,
                        SportsId = evm.SportsId,
                        PicturePath = filepath
                    };
                    db.Entry(player).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    Player player = new Player
                    {
                        PlayerId = evm.PlayerId,
                        PlayerName = evm.PlayerName,
                        JoinDate = evm.JoinDate,
                        Grade = evm.Grade,
                        SportsId = evm.SportsId,
                        PicturePath = filepath
                    };
                    db.Entry(player).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Sports = new SelectList(db.Sports, "SportsId", "SportsName", evm.SportsId);
            return View(evm);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Player player = db.Players.Find(id);

            string file_name = player.PicturePath;
            string path = Server.MapPath(file_name);
            FileInfo file = new FileInfo(path);
            if (file.Exists)//check file exsit or not  
            {
                file.Delete();
            }
            db.Players.Remove(player);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Evidence_01/Views/Players/Create.cshtml
@model Evidence_01.Models.ViewModels.PlayersViewModel
@{
    /**/

    ViewBag.Title = "Create";
}

<div class="row mt-5">
    <div class="col">
        @using (Html.BeginForm("Create", "Players", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken();
            <h2>Create Player</h2>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group row">
                @Html.LabelFor(model => model.PlayerName, htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PlayerName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PlayerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Grade, "----Select one----", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.SportsId, "Sports", htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SportsId, ViewBag.Sports as SelectList, "----Select one----", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SportsId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.JoinDate, htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.JoinDate, new { htmlAttributes = new { @class = "form-control",Type="date"} })
                    @Html.ValidationMessageFor(model => model.JoinDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Picture, new { @class = "form-control", type = "file" })
                    @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">

                <div class="offset-2 col-md-10">
                    <input type="reset" class="btn btn-warning" value="Reset" />
                    <input type="submit" class="btn btn-primary" value="Save data" />
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-info" })
</div>

Evidence_01/Views/Players/Delete.cshtml
@model Evidence_01.Models.Player

@{
    ViewBag.Title = "Delete";
}



<h3 class="alert alert-danger">Are you sure you want to delete this?</h3>
<div>
    <h4 class="alert alert-danger">Player</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sports.SportsName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sports.SportsName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JoinDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JoinDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PicturePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PicturePath)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Evidence_01/Views/Players/Edit.cshtml
@model Evidence_01.Models.ViewModels.PlayersViewModel
@{
    ViewBag.Title = "Edit";
}

<div class="row mt-5">
    <div class="col">
        @using (Html.BeginForm("Edit", "Players", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken();
            <h2>Edit Player</h2>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PlayerId)
            @Html.HiddenFor(model => model.PicturePath)
            <div class="form-group row">
                @Html.LabelFor(model => model.PlayerName, htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PlayerName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PlayerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Grade, "----Select one----", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.SportsId, "SportsId", htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SportsId, ViewBag.Sports as SelectList, "----Select one----", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SportsId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.JoinDate, htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.JoinDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.JoinDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "col-form-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Picture, new { @class = "form-control", type = "file" })
                    @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">

                <div class="col-md-offset-2 col-md-10">
                    <input type="reset" class="btn btn-secondary" value="Reset Values" />
                    <input type="submit" class="btn btn-primary" value="Update data" />
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-info" })
</div>

Evidence_01/Views/Players/Index.cshtml
@model IEnumerable<Evidence_01.Models.Player>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-12">
        <h2>Player List</h2>
        <div class="text-right">
            @Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-primary" })
        </div>
        <table class="table table-bordered table-striped table-hover" style="margin-top:5px;">
            <thead>
                <tr>
                    <th>Player Name</th>
                    <th>Sports Name</th>
                    <th>Join Date</th>
                    <th>Grade</th>
                    <th>Picture</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.PlayerName</td>
                        <td>@item.Sports.SportsName</td>
                        <td>@item.JoinDate.ToShortDateString()</td>
                        <td>@item.Grade</td>
                        <td>
                            <img src="@Url.Content(item.PicturePath)" width="40" />
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.PlayerId }, new { @class = "btn btn-primary btn-sm" })
                            @Html.ActionLink("Delete", "Delete", new { id = item.PlayerId }, new { @class = "btn btn-danger btn-sm" })

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>